
-- DROP TABLES
DROP TABLE DW_CALENDAR_DIMENSION CASCADE CONSTRAINTS PURGE;
DROP TABLE DW_PAYMENT_DIMENSION CASCADE CONSTRAINTS PURGE;
DROP TABLE DW_CUSTOMER_DIMENSION CASCADE CONSTRAINTS PURGE;
DROP TABLE DW_VEHICLE_DIMENSION CASCADE CONSTRAINTS PURGE;
DROP TABLE DW_TEMP_BOOKING CASCADE CONSTRAINTS PURGE;
DROP TABLE DW_TEMP_REGISTRATION CASCADE CONSTRAINTS PURGE;
DROP TABLE DW_REVENUE_FACT CASCADE CONSTRAINTS PURGE;

DROP TABLE GG_COUNTRY CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_LOCATION CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_DEPARTMENT CASCADE CONSTRAINTS PURGE; 
DROP TABLE GG_MANAGER CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_EMPLOYEES CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_BUSINESS CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_CUSTOMERS CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_RETAILERS CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_SMARTCARD CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_PLAN CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_CONTRACT CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_PAYMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_REGISTER CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_EXTRAFEE CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_POD CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_VEHICLE CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_BOOKING CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_PRICING CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_SUPPLIER CASCADE CONSTRAINTS PURGE;
DROP TABLE GG_INSURANCE CASCADE CONSTRAINTS PURGE;


-- Create GG_COUNTRY table 
CREATE TABLE GG_COUNTRY ( 
	country_id NUMBER (4) NOT NULL PRIMARY KEY, 
	country_name VARCHAR2(255)
);

-- Create GG_LOCATION table
CREATE TABLE GG_LOCATION (
	location_id NUMBER (4) NOT NULL PRIMARY KEY, 
	street VARCHAR2(255), 
	state VARCHAR2(255), 
	country_id REFERENCES GG_COUNTRY(COUNTRY_ID),
	postal_code VARCHAR2(255),
	suburb VARCHAR2(255)
);

-- GG_DEPARTMENT TABLE:
CREATE TABLE GG_DEPARTMENT (  
	DEPARTMENT_ID VARCHAR2(255) NOT NULL PRIMARY KEY,   
	DEPARTMENT_NAME VARCHAR2(255),   
	LOCATION_ID REFERENCES GG_LOCATION
);

-- GG_MANAGER TABLE:
CREATE TABLE GG_MANAGER ( 
	MANAGER_ID NUMBER(4) NOT NULL PRIMARY KEY, 
	DEPARTMENT_ID REFERENCES GG_DEPARTMENT(DEPARTMENT_ID) 
);

--GG_EMPLOYEES TABLE:
CREATE TABLE GG_EMPLOYEES (   
	EMPLOYEE_ID NUMBER(6) NOT NULL PRIMARY KEY,  
	FIRST_NAME VARCHAR2(255),  
	LAST_NAME VARCHAR2(255),  
	MANAGER_ID REFERENCES GG_MANAGER,  
	DEPARTMENT_ID REFERENCES GG_DEPARTMENT 
);

-- GG_PLAN
CREATE TABLE GG_PLAN (
	Plan_ID NUMBER(6)
	CONSTRAINT PLAN_TBL_PK PRIMARY KEY,
	Plan_Type VARCHAR(25),
	Monthly_Price NUMBER(25)
);

-- GG_RETAILERS
CREATE TABLE GG_RETAILERS ( 
	retailer_id NUMBER(6) PRIMARY KEY, 
	retailer_name VARCHAR2(255),  
	location_id REFERENCES GG_LOCATION,  
	address VARCHAR2(255) 
);

--GG_POD
CREATE TABLE GG_POD ( 
	POD_ID VARCHAR2(10) NOT NULL PRIMARY KEY, 
	STREET VARCHAR2(255), 
	LOCATION_ID REFERENCES GG_LOCATION 
);

--GG_CONTRACT TABLE
CREATE TABLE GG_Contract( 
	Contract_ID NUMBER(8) NOT NULL PRIMARY KEY, 
	Start_Date DATE, 
	End_Date DATE, 
	Plan_ID REFERENCES GG_Plan  
);


-- GG_BUSINESS
CREATE TABLE GG_Business(
	Business_ID NUMBER(6) NOT NULL PRIMARY KEY,
	Trading_Name VARCHAR2(255),
	Company_Name VARCHAR2(255),
	Address VARCHAR2(255),
	Contract_ID REFERENCES GG_Contract
);


--GG_PAYMENT
CREATE TABLE GG_PAYMENT (
	PAYMENT_ID NUMBER(4) NOT NULL PRIMARY KEY,
	CARD_NUMBER VARCHAR2(255),
	EXPIRY_DATE DATE,
	AMOUNT_IN_AUD DECIMAL(6,2),
	PAYMENT_DATE DATE
);

--GG_CUSTOMERS TABLE
CREATE TABLE GG_CUSTOMERS (
	customer_id NUMBER (8) PRIMARY KEY,
	first_name VARCHAR2(255),
	last_name VARCHAR2(255),
	phone_no NUMBER(10),
	email VARCHAR2(255),
	license_no NUMBER(8),
	business_id REFERENCES GG_BUSINESS
);

--GG_SMARTCARD TABLE
CREATE TABLE GG_SMARTCARD (
	card_id NUMBER(8) PRIMARY KEY,
	customer_id REFERENCES GG_CUSTOMERS, 
	retailer_id REFERENCES GG_RETAILERS
);

--GG_REGISTER TABLE
CREATE TABLE GG_REGISTER (
	start_date DATE,
	end_date DATE,
	customer_id REFERENCES GG_CUSTOMERS,
	plan_id REFERENCES GG_PLAN,
	payment_id REFERENCES GG_PAYMENT,
	PRIMARY KEY (customer_id, plan_id)
);


--GG_Vehicle table 
CREATE TABLE GG_VEHICLE(  
	Vehicle_ID NUMBER(6) PRIMARY KEY,
	POD_ID REFERENCES GG_POD, 
	Type VARCHAR2(25),  
	Colour VARCHAR2(25),  
	Description VARCHAR2(255), 
	Capacity NUMBER(1),  
	Fuel_Type VARCHAR2(25),  
	Registration_Plate VARCHAR2(6),  
	Transmission VARCHAR2(10),  
	Special_Features VARCHAR(250), 
	Pet_Allowed VARCHAR2(10),
	Availability VARCHAR2(10)
);

--GG_Pricing table 
CREATE TABLE GG_PRICING (
	Vehicle_ID REFERENCES GG_VEHICLE,
	Plan_ID REFERENCES GG_PLAN,
	Rent_per_hour DECIMAL(6,2),
	Rent_per_day DECIMAL(6,2)
);


--GG_SUPPLIER
CREATE TABLE GG_SUPPLIER (
	SUPPLIER_ID VARCHAR2(255) NOT NULL PRIMARY KEY,
	VEHICLE_ID REFERENCES GG_VEHICLE,
	MANUFACTURER_NAME VARCHAR2(255)
);
--GG_INSURANCE
CREATE TABLE GG_INSURANCE (
	INSURANCE_ID VARCHAR2(255) NOT NULL PRIMARY KEY,
	INSURANCE_PENALTY NUMBER(6),
	VEHICLE_ID REFERENCES GG_VEHICLE
);

--GG_EXTRA_FEE TABLE
CREATE TABLE GG_Extrafee(
	Fee_ID NUMBER(8) NOT NULL PRIMARY KEY,
	Fee_Type VARCHAR2(40),
	Amount DECIMAL(6,2)
);

--GG_BOOKING TABLE
CREATE TABLE GG_Booking(
	Booking_ID NUMBER(8) NOT NULL PRIMARY KEY,
	Start_Time TIMESTAMP,
	End_Time TIMESTAMP,
	Discount NUMBER(5,2),
	Customer_ID REFERENCES GG_Customers,
	Vehicle_ID REFERENCES GG_Vehicle,
	Plan_ID REFERENCES GG_Plan,
	Fee_ID REFERENCES GG_Extrafee,
	Payment_ID REFERENCES GG_Payment
);
